### ISSUE TITLE
Make it clear that username passwd shld be set

### ISSUE THREAD

**Issue by shivaram** [amplab/training#29]
For spark streaming, twitter username passwd should be set in a file

**Comment by shivaram** [comment]
Fixed in https://github.com/amplab/training/commit/225c77a621ada3964dbd25b3755c0d8f1f96e7ff and https://github.com/amplab/training/commit/0e2a2fba67a4c039c4bae2d03cd7abc40977df22

**Comment by sivarani** [comment]
Hi tdas, is it possible to run spark 24/7, i am using updateStateByKey and i am streaming 3lac records in 1/2 hr, i am not getting the correct result also i am not not able to run spark streaming for 24/7 after hew hrs i get array out of bound exception even if i am not streaming anything? btw will the streaming end if i am not streaming anything for a few minutes? Please help me out here

Also is it possible to delete state? since its growing exponentially, also not all the data are updated.. at some point we have to reset it na? how to do that.. i am able to work with batch processing using spark successfully but streaming is quite a mystery for me
