### ISSUE TITLE
Do we need to set MASTER when launching spark-shell?

### ISSUE THREAD

**Issue by JoshRosen** [amplab/training#5]
In the tutorial, `spark-shell` is launched without any arguments and before any environment variables are set.

Shouldn't we have users do something like

``` bash
MASTER=spark://server:port /root/spark/spark-shell
```

so that jobs run on the cluster?  Was this somehow handled automatically on the AMPCamp AMI?

**Comment by pwendell** [comment]
I think that Shivaram made it so that both this and the default filesystem
are handled on the image automatically. We should definitely note these
down to make sure that this happens again (maybe add a TODO in the
tutorial).

**Comment by JoshRosen** [comment]
Is there a reason why we don't do this on the default Spark AMI?

**Comment by pwendell** [comment]
Ya frankly seems like both would be useful for that, given that we setup
the filesystem.
- Patrick

**Comment by mateiz** [comment]
Maybe we modified conf/spark-env.sh on that one to set MASTER.

Matei

**Comment by shivaram** [comment]
Yes, we will set the MASTER env variable in conf/spark-env.sh. I'll also make sure to add hadoop conf to the class path so that S3 keys and fs.default.name work. And I just added it to the spark-ec2 repo, so it should work out of the box in all AMIs from now (https://github.com/shivaram/spark-ec2/commit/6a17f585c84fed0ca4275237afb0838526c7713d)
